development:
  theme_id: "151913095"
  bucket_size: 40
  refill_rate: 2

production:
  theme_id: "93393668"
  bucket_size: 40
  refill_rate: 2

whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/